import type { ChatLLM } from "../../config/llm.js";
import { readFile } from "node:fs/promises";
import type {
  FlowExecutionResult,
  ValidationResult,
} from "../../types/OrchestrationTypes.js";

/**
 * ContentValidator
 * Intelligent validator that uses LLM to check content quality
 */
export class ContentValidator {
  private llm: ChatLLM;

  constructor(llm: ChatLLM) {
    this.llm = llm;
  }

  /**
   * Validate content quality using LLM
   * @param flowResults - Map of flow execution results
   * @returns Array of validation results
   */
  async validate(
    flowResults: Map<string, FlowExecutionResult>,
  ): Promise<ValidationResult[]> {
    const results: ValidationResult[] = [];

    for (const [flowName, result] of flowResults) {
      // Skip flows that didn't complete successfully or have no JSON output
      if (!result.success || !result.outputs.intermediateJson) {
        continue;
      }

      try {
        // Load the JSON content
        const jsonContent = await readFile(
          result.outputs.intermediateJson,
          "utf-8",
        );
        const data = JSON.parse(jsonContent);

        // Build prompt for LLM validation
        const prompt = this.buildValidationPrompt(flowName, data);

        // Call LLM to validate content
        // Parse LLM response
        const validation = this.parseValidationResponse(
          await this.llm.complete(prompt),
        );

        results.push({
          validationType: "contentQuality",
          flowName,
          passed: validation.valid,
          details: validation.reasoning,
          warnings: validation.issues.length > 0 ? validation.issues : undefined,
          llmReasoning: validation.reasoning,
        });
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : String(error);
        results.push({
          validationType: "contentQuality",
          flowName,
          passed: false,
          details: `LLM validation failed: ${errorMsg}`,
          warnings: [`Error during LLM validation: ${errorMsg}`],
        });
      }
    }

    return results;
  }

  /**
   * Build validation prompt for LLM
   */
  private buildValidationPrompt(flowName: string, data: any): string {
    const promptLines = [
      `You are a data quality validator. Analyze the following JSON generated by the flow "${flowName}".`,
      ``,
      `VALIDATION CRITERIA:`, 
      `1. Required fields must not be empty (null, undefined, or empty strings)`, 
      `2. Data must make semantic sense for the context`, 
      `3. Arrays should have at least 1 element where logically expected.`, 
      `4. **Special Note for BDD Scenarios**: For flows extracting BDD scenarios, it is expected and acceptable for 
scenariosBddModular
 and 
scenariosBddIntegration
 arrays to contain identical or very similar scenarios. This duplication should NOT be flagged as an issue.`, 
      `5. No placeholder values like "TODO", "TBD", "PLACEHOLDER", etc.`, 
      `6. String values should be meaningful, not generic defaults`, 
      `7. Numeric values should be reasonable for their context`, 
      ``,
      `JSON TO VALIDATE:`, 
      `${JSON.stringify(data, null, 2)}`,
      ``,
      `RESPOND ONLY with a JSON object in this exact format (no additional text):`,
      `{`,
      `  "valid": true or false,`,
      `  "reasoning": "Brief explanation of your assessment",`,
      `  "issues": ["Array of specific issues found, or empty array if none"]`,
      `}`
    ];
    return promptLines.join('\n');
  }

  /**
   * Parse LLM validation response
   */
  private parseValidationResponse(response: string): {
    valid: boolean;
    reasoning: string;
    issues: string[];
  } {
    try {
      // Extract JSON from response (handle potential markdown code blocks)
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        throw new Error("No JSON found in LLM response");
      }

      const parsed = JSON.parse(jsonMatch[0]);

      return {
        valid: Boolean(parsed.valid),
        reasoning: String(parsed.reasoning || "No reasoning provided"),
        issues: Array.isArray(parsed.issues)
          ? parsed.issues.map(String)
          : [],
      };
    } catch (error) {
      console.error("Failed to parse LLM response:", response);
      return {
        valid: false,
        reasoning: `Failed to parse LLM response: ${error instanceof Error ? error.message : String(error)}`,
        issues: ["LLM response parsing error"],
      };
    }
  }
}
